### PR TITLE
Version updates

### PR DESCRIPTION
**Pull request by ibiternas**
A couple of version of dependencies are becoming really obsolete.

### CODE REVIEW

**Comment by droanrishi** [comment]
+1

**Comment by fullstackhacker** [comment]
+1

**Comment by angeloashmore** [comment]
Thanks for bringing this up. 👍 

I'll take a look at this and see what else I can do to freshen up the codebase in a day or two.

In the meantime, is there anything broken for you at the moment?

**Comment by ibiternas** [comment]
Not broken, just giving deprecation warnings, however won't take long time before a version conflict will emerge.  @angeloashmore  Thanks for prompt reply.

**Comment by angeloashmore** [comment]
Sorry, took a little longer than expected to take a look at this. The changes look good!

**Comment by angeloashmore** [comment]
Quick update: I pushed a few changes to the repo.

- [x] Replace `standard` with `prettier`
- [x] Update babel presets to `babel-preset-env`
- [x] Move to Rollup for bundling (wow, saved a huge amount of space here!)
- [x] Add `module` and `browser` to `package.json`
- [x] Add minification with `babel-minify` (again, saved a bunch of space here)

v0.4.0 has been published. Please test and let me know if you run into issues!

Thanks 😄

**Pull request merged**
